name: Production Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build container image
        run: DOCKER_BUILDKIT=1 docker build --build-arg GH_TOKEN=${{ secrets.KIWI_TOKEN }} -t registry.digitalocean.com/athenabot/proxy-rater-service:latest .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_KEY }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials and Push Image
        run: doctl registry login --expiry-seconds 1200 && docker push registry.digitalocean.com/athenabot/proxy-rater-service:latest

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 athena

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl rollout restart deployments proxy-rater -n general

      - name: Verify deployment
        run: kubectl rollout status deployments proxy-rater -n general
